### ISSUE TITLE
cgi_cookie_set does not work

### ISSUE THREAD

**Issue by GoogleCodeExporter** [blong42/clearsilver#10] opened 2016-01-08 18:48 UTC
```
What steps will reproduce the problem?
1. cgi_cookie_set(cgi, "cgi_cookie_test", "hellocgi", "/", "localhost", "Sat. 
06 Oct 2013 08:30:00", 1, 0)
2. http://localhost/cgi-bin/hellocs
3. Set-Cookie: cgi_cookie_test=hellocgi; path=/; expires=Sat. 06 Oct 2013 
08:30:00; domain=localhost Content-Type: text/html 
HTTP_COOKIE 
SESS29af1facda0a866a687d5055f2fade2c=EaXgcoenUyy9_AvsvrFvniUv6PjfS2n6aS3iunlvLu0
; pla3412=123456; pla3412_salt=lt260tdkeqc

What is the expected output? What do you see instead?
there is cgi_cookie_set in HTTP_COOKIE, but nope.

What version of the product are you using? On what operating system?
clearsilver-0.10.5
Linux 3.5.2-gentoo x86_64 Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz 
GenuineIntel GNU/Linux

Please provide any additional information below.

```

Original issue reported on code.google.com by `xiangzha...@gmail.com` on 28 Sep 2012 at 4:43

**Comment by blong42** [comment] 2017-07-14 22:54
closing as unable to reproduce

**Closed by blong42** 2017-07-14 22:54 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
